Fix 'unused-result' warning on GCC
Fixes a GCC warning that becomes an error when using `-Werror`:

death_handler.cc: In static member function ‘static void Debug::DeathHandler::HandleSignal(int, void*, void*)’:
death_handler.cc:709:8: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
  709 |   write(STDERR_FILENO, &end, 1);
      |   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~

I.e. the return value of write() must be retrieved, but in
current code it is not.

This chane simply keeps the same behavior, but making it explicit,
thus it conveys better the intention, and avoids the warning.